<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TrackAnalysisWorker-3d082747-2e4a-43e1-b7b1-8bdc880a801b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Clients/" />
    <Folder Include="Clients/Implementations/" />
    <Folder Include="Clients/Interfaces/" />
    <Folder Include="Models/" />
    <Folder Include="Services/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <ProjectReference Include="../SpotifyPlaylistSorter.Business/SpotifyPlaylistSorter.Business.csproj" />
  </ItemGroup>
</Project>
